// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmjmqexufftqwasezqhu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtam1xZXh1ZmZ0cXdhc2V6cWh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3ODA5OTAsImV4cCI6MjA3NDM1Njk5MH0.0QbkIVxBy30JUEVrZlHsC271HZ-g57L4Cs8zBIFkhbI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});